// <auto-generated />
using System;
using CSOPS.DevChallenge.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSOPS.DevChallenge.Migrations
{
    [DbContext(typeof(ChallengeContext))]
    [Migration("20241019200301_UpdateChatInfoTable")]
    partial class UpdateChatInfoTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CSOPS.DevChallenge.Context.Entities.ChatInfo", b =>
                {
                    b.Property<string>("ChatId")
                        .HasMaxLength(35)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnyAttendantAssigned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWaiting")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastMessageTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberAssignedName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId");

                    b.ToTable("ChatInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
