// <auto-generated />
using CSOPS.DevChallenge.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSOPS.DevChallenge.Migrations
{
    [DbContext(typeof(ChallengeContext))]
    [Migration("20240911155046_AddedChatInfosTable")]
    partial class AddedChatInfosTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSOPS.DevChallenge.Context.Entities.ChatInfo", b =>
                {
                    b.Property<string>("ChatId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAnyAttendantAssigned")
                        .HasColumnType("bit");

                    b.HasKey("ChatId");

                    b.ToTable("ChatInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
